# Generated by Django 4.1.7 on 2023-04-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Management Group',
                'verbose_name_plural': 'Management Groups',
            },
        ),
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Model Category',
                'verbose_name_plural': 'Model Categories',
            },
        ),
        migrations.CreateModel(
            name='ModelManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=7, verbose_name='Short Name')),
                ('full_name', models.CharField(max_length=20, verbose_name='Full Name')),
                ('management_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samapp.managementgroup', verbose_name='Management Group')),
            ],
            options={
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Units',
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samapp.modelcategory', verbose_name='Category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samapp.modelmanufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Asset Model',
                'verbose_name_plural': 'Asset Models',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('warranty', models.DateField(verbose_name='Warranty')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('order_number', models.CharField(max_length=10, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('deployed', 'Deployed'), ('in_storage', 'In Storage'), ('ready_for_deployment', 'Ready for Deployment'), ('malfunction', 'Malfunction'), ('recycled', 'Recycled'), ('ready_for_recycle', 'Ready for Recycle')], max_length=20, verbose_name='Status')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samapp.businessunit', verbose_name='Business Unit')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='samapp.assetmodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
